CREATE DATABASE IF NOT EXISTS api_db;
USE api_db;

CREATE TABLE IF NOT EXISTS temperature_logs (
  id INT AUTO_INCREMENT PRIMARY KEY,
  celsius FLOAT NOT NULL,
  fahrenheit FLOAT NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
